version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: loteca
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - loteca-mysql:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/teams.sql:/docker-entrypoint-initdb.d/3.sql
      - ./scripts/stadiums.sql:/docker-entrypoint-initdb.d/4.sql
      - ./scripts/competitions.sql:/docker-entrypoint-initdb.d/5.sql
      - ./scripts/seasons.sql:/docker-entrypoint-initdb.d/6.sql
    networks:
      - loteca-network
  admin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    links:
      - mysql
    ports:
      - 8081:80
    networks:
      - loteca-network
  backend:
    image: loteca-backend
    restart: 'no'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - loteca-network
volumes:
  loteca-mysql:
networks:
  loteca-network: