version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: loteca
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - loteca-mysql:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - loteca-network
volumes:
  loteca-mysql:
networks:
  loteca-network:
