version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: loteca
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - loteca-network
  backend:
    image: giancarlobastos/loteca:1.0.17
    container_name: backend
    restart: 'always'
    environment:
      - TOPIC=loteca
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - mysql
    networks:
      - loteca-network
  route53:
    image: giancarlobastos/route53-dyndns:1.2.1
    container_name: route53
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=AKIA5QBALE2U4EWT4KBW
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_CONNECTION_REGION=sa-east-1
      - ROUTE53_DOMAIN_A_RECORD=loteca.click
      - ROUTE53_UPDATE_FREQUENCY=10800
      - ROUTE53_RECORD_TTL=300
  nginx-server:
    image: nginx:1.15-alpine
    container_name: nginx-server
    ports:
      - "80:80" 
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './app-ads.txt:/www/data/app-ads.txt'
      - './privacy.txt:/www/data/privacy.txt'
      - './terms.txt:/www/data/terms.txt'
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks: 
      - "loteca-network"
    depends_on: 
      - backend
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  mysql-volume:
networks:
  loteca-network:
